# Generated by Django 5.0.6 on 2024-07-02 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(default=0),
        ),
    ]
