# Generated by Django 5.0.2 on 2024-07-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_rename_drivers_driver_rename_drivers_quote_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='quote_id',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
