# Generated by Django 5.0.2 on 2024-07-31 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_customer_quote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='quote_id',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='quote_id',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
