# Generated by Django 5.0.2 on 2024-07-31 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_driver_quote_id_vehicle_quote_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='Driver_Relation',
            field=models.CharField(choices=[('SELF', 'Self'), ('GRANDFATHER', 'Grandfather'), ('GRANDMOTHER', 'Grandmother'), ('SPOUSE', 'Spouse'), ('DOMESTIC PARTNER', 'Domestic Partner'), ('SON', 'Son'), ('DAUGHTER', 'Daughter'), ('FATHER', 'Father'), ('MOTHER', 'Mother'), ('FATHER IN LAW', 'Father in law'), ('MOTHER IN LAW', 'Mother in Law'), ('FIANCE', 'Fiance'), ('FRIEND', 'Friend'), ('OTHER', 'Other')], default='SELF', max_length=16),
        ),
    ]
