# Generated by Django 5.0.7 on 2024-08-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0005_alter_driver_driver_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='Driver_First_Name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='Driver_Last_Name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='Driver_Relation',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='Drivers_License_Number',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='Drivers_License_State',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='Drivers_License_Status',
        ),
        migrations.AlterField(
            model_name='driver',
            name='education',
            field=models.CharField(choices=[('LESS THAN HIGHSCHOOL', 'Less than highschool'), ('HIGHSCHOOL', 'Highschool'), ('VOCATIONAL', 'Vocational'), ('ASSOCIATE', 'Associate'), ('Bachelors', 'Bachelors'), ('PHD', 'Phd'), ('DOCTORS', 'Doctor'), ('LAWYER', 'Lawyer')], max_length=35),
        ),
        migrations.AlterField(
            model_name='driver',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NONBINARY', 'NonBinary'), ('NOANSWER', 'Prefer Not to Answer')], max_length=30),
        ),
        migrations.AlterField(
            model_name='driver',
            name='job_status',
            field=models.CharField(choices=[('FULL_TIME_EMPLOYED', 'Full Time Employed'), ('PART_TIME_EMPLOYED', 'Part Time Employed'), ('STUDENT', 'Student'), ('HOMEMAKER', 'Homemaker'), ('UNEMPLOYED', 'Unemployed')], max_length=50),
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_relation',
            field=models.CharField(choices=[('SELF', 'Self'), ('GRANDFATHER', 'Grandfather'), ('GRANDMOTHER', 'Grandmother'), ('SPOUSE', 'Spouse'), ('DOMESTIC PARTNER', 'Domestic Partner'), ('SON', 'Son'), ('DAUGHTER', 'Daughter'), ('FATHER', 'Father'), ('MOTHER', 'Mother'), ('FATHER IN LAW', 'Father in law'), ('MOTHER IN LAW', 'Mother in Law'), ('FIANCE', 'Fiance'), ('FRIEND', 'Friend'), ('OTHER', 'Other')], default='SELF', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='drivers_license_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='drivers_license_state',
            field=models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DC', 'Washington D.C.'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='drivers_license_status',
            field=models.CharField(choices=[('ACTIVE LICENSE', 'Active License'), ('LEARNERS PERMIT', 'Permit License'), ('COMMERCIAL LICENSE', 'Commerical License'), ('FOREIGN LICENSE', 'Foreign License'), ('INTERNATION LICENSE', 'International License'), ('SUSPENDED LICENSE', 'Suspended License'), ('EXPIRED LICENSE', 'Expired License'), ('NOT LICENSED TO DRIVE', 'Not licensed to drive')], max_length=50, null=True),
        ),
    ]
