# Generated by Django 5.0.7 on 2024-08-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0006_remove_driver_driver_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='quote_id',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
