# Generated by Django 5.0.7 on 2024-08-25 22:52

import phone_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0008_alter_customer_quote_id_alter_vehicle_quote_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='telephone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
