# Generated by Django 5.0.2 on 2024-08-26 04:37

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0008_alter_customer_quote_id_alter_vehicle_quote_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='telephone_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region='US'),
            preserve_default=False,
        ),
    ]
