# Generated by Django 5.0.7 on 2024-08-26 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0009_alter_customer_telephone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='telephone_number',
        ),
    ]
