# shared constants
STATE_OPTIONS = (
    ("AL", "Alabama"),
    ("AK", "Alaska"),
    ("AZ", "Arizona"),
    ("AR", "Arkansas"),
    ("CA", "California"),
    ("CO", "Colorado"),
    ("CT", "Connecticut"),
    ("DC", "Washington D.C."),
    ("DE", "Delaware"),
    ("FL", "Florida"),
    ("GA", "Georgia"),
    ("HI", "Hawaii"),
    ("ID", "Idaho"),
    ("IL", "Illinois"),
    ("IN", "Indiana"),
    ("IA", "Iowa"),
    ("KS", "Kansas"),
    ("LA", "Louisiana"),
    ("ME", "Maine"),
    ("MD", "Maryland"),
    ("MA", "Massachusetts"),
    ("MI", "Michigan"),
    ("MN", "Minnesota"),
    ("MS", "Mississippi"),
    ("MO", "Missouri"),
    ("MT", "Montana"),
    ("NE", "Nebraska"),
    ("NV", "Nevada"),
    ("NH", "New Hampshire"),
    ("NJ", "New Jersey"),
    ("NM", "New Mexico"),
    ("NY", "New York"),
    ("NC", "North Carolina"),
    ("ND", "North Dakota"),
    ("OH", "Ohio"),
    ("OK", "Oklahoma"),
    ("OR", "Oregon"),
    ("PA", "Pennsylvania"),
    ("PR", "Puerto Rico"),
    ("RI", "Rhode Island"),
    ("SC", "South Carolina"),
    ("SD", "South Dakota"),
    ("TN", "Tennessee"),
    ("TX", "Texas"),
    ("UT", "Utah"),
    ("VT", "Vermont"),
    ("VA", "Virginia"),
    ("WA", "Washington"),
    ("WI", "Wisconsin"),
    ("WY", "Wyoming"),
)

# driver model constants
DRIVER_RELATION_OPTIONS = (
    ("SELF", "Self"),
    ("GRANDFATHER", "Grandfather"),
    ("GRANDMOTHER", "Grandmother"),
    ("SPOUSE", "Spouse"),
    ("DOMESTIC PARTNER", "Domestic Partner"),
    ("SON", "Son"),
    ("DAUGHTER", "Daughter"),
    ("FATHER", "Father"),
    ("MOTHER", "Mother"),
    ("FATHER IN LAW", "Father in law"),
    ("MOTHER IN LAW", "Mother in Law"),
    ("FIANCE", "Fiance"),
    ("FRIEND", "Friend"),
    ("OTHER", "Other"),
)

JOB_STATUS_OPTIONS = (
    ("FULL_TIME_EMPLOYED", "Full Time Employed"),
    ("PART_TIME_EMPLOYED", "Part Time Employed"),
    ("STUDENT", "Student"),
    ("HOMEMAKER", "Homemaker"),
    ("UNEMPLOYED", "Unemployed"),
)

DRIVERS_LICENSE_STATUS = (
    ("ACTIVE LICENSE", "Active License"),
    ("LEARNERS PERMIT", "Permit License"),
    ("COMMERCIAL LICENSE", "Commerical License"),
    ("FOREIGN LICENSE", "Foreign License"),
    ("INTERNATION LICENSE", "International License"),
    ("SUSPENDED LICENSE", "Suspended License"),
    ("EXPIRED LICENSE", "Expired License"),
    ("NOT LICENSED TO DRIVE", "Not licensed to drive"),
)

EDUCATION_OPTIONS = (
    ("LESS THAN HIGHSCHOOL", "Less than highschool"),
    ("HIGHSCHOOL", "Highschool"),
    ("VOCATIONAL", "Vocational"),
    ("ASSOCIATE", "Associate"),
    ("Bachelors", "Bachelors"),
    ("PHD", "Phd"),
    ("DOCTORS", "Doctor"),
    ("LAWYER", "Lawyer"),
)

GENDER_OPTIONS = (
    ("MALE", "Male"),
    ("FEMALE", "Female"),
    ("NONBINARY", "NonBinary"),
    ("NOANSWER", "Prefer Not to Answer"),
)
